name: CI Pipeline

on:
  push:
    branches:
      - "main"
    paths:
      - 'techdom-collector/**'
      - 'techdom-emulator/**'
  pull_request:
    branches:
      - "main"
    paths:
      - 'techdom-collector/**'
      - 'techdom-emulator/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'corretto'

      - name: Set up environment variables
        run: |
          echo DEV_MYSQL_ROOT_PASSWORD=${{ secrets.DEV_MYSQL_ROOT_PASSWORD }} >> .env
          echo DEV_MYSQL_DATABASE_NAME=${{ secrets.DEV_MYSQL_DATABASE_NAME }} >> .env
          echo DEV_MYSQL_USER=${{ secrets.DEV_MYSQL_USER }} >> .env
          echo DEV_MYSQL_PASSWORD=${{ secrets.DEV_MYSQL_PASSWORD }} >> .env
          echo DEV_MYSQL_URL=${{ secrets.DEV_MYSQL_URL }} >> .env
          echo DEV_MYSQL_TIME_ZONE=${{ secrets.DEV_MYSQL_TIME_ZONE }} >> .env

      - uses: actions/checkout@v3
      - name: make collector application-dev.yml
        if: contains(github.ref, 'main')
        run: |
          touch .techdom-collector/src/main/resources
          cd .techdom-collector/src/main/resources
          touch ./application.yml
          echo "${{ secrets.TECHDOM_COLLECTOR_YML }}" > ./application.yml
        shell: bash

      - uses: actions/checkout@v3
      - name: make emulator application-dev.yml
        if: contains(github.ref, 'main')
        run: |
          touch .techdom-emulator/src/main/resources
          cd .techdom-emulator/src/main/resources
          touch ./application.yml
          echo "${{ secrets.TECHDOM_EMULATOR_YML }}" > ./application.yml
        shell: bash

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@417ae3ccd767c252f5661f1ace9f835f9654f2b5

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle Wrapper
        run: ./gradlew build

      - name: Build and Deploy
        if: success()
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          techdom_COLLECTOR_YML: ${{ secrets.techdom_COLLECTOR_YML }}
          techdom_EMULATOR_YML: ${{ secrets.techdom_EMULATOR_YML }}
        run: |
          echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
          
          if [[ $(git diff --name-only HEAD^ HEAD) =~ ^techdom-collector/ ]]; then
            echo "Building and deploying techdom-collector"
            cd techdom-collector

            docker build -t $DOCKER_USERNAME/techdom-collector:latest .
            docker push $DOCKER_USERNAME/techdom-collector:latest
            cd ..
          fi

          if [[ $(git diff --name-only HEAD^ HEAD) =~ ^techdom-emulator/ ]]; then
            echo "Building and deploying techdom-emulator"
            cd techdom-emulator
          
            docker build -t $DOCKER_USERNAME/techdom-emulator:latest .
            docker push $DOCKER_USERNAME/techdom-emulator:latest
            cd ..
          fi

