name: CI/CD Pipeline

on:
  push:
    branches:
      - "main"
    paths:
      - 'techdom-collector/**'
      - 'techdom-emulator/**'
  pull_request:
    branches:
      - "main"
    paths:
      - 'techdom-collector/**'
      - 'techdom-emulator/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'corretto'

      - name: Set up environment variables
        run: |
          echo DEV_MYSQL_ROOT_PASSWORD=${{ secrets.DEV_MYSQL_ROOT_PASSWORD }} >> .env
          echo DEV_MYSQL_DATABASE_NAME=${{ secrets.DEV_MYSQL_DATABASE_NAME }} >> .env
          echo DEV_MYSQL_USER=${{ secrets.DEV_MYSQL_USER }} >> .env
          echo DEV_MYSQL_PASSWORD=${{ secrets.DEV_MYSQL_PASSWORD }} >> .env
          echo DEV_MYSQL_URL=${{ secrets.DEV_MYSQL_URL }} >> .env
          echo DEV_MYSQL_TIME_ZONE=${{ secrets.DEV_MYSQL_TIME_ZONE }} >> .env

      - uses: actions/checkout@v3
      - name: make collector application-dev.yml
        if: contains(github.ref, 'main')
        run: |
          cd techdom-collector/src/main/resources
          touch ./application.yml
          echo "${{ secrets.TECHDOM_COLLECTOR_YML }}" > ./application.yml
        shell: bash

      - uses: actions/checkout@v3
      - name: make emulator application-dev.yml
        if: contains(github.ref, 'main')
        run: |
          cd techdom-emulator/src/main/resources
          touch ./application.yml
          echo "${{ secrets.TECHDOM_EMULATOR_YML }}" > ./application.yml
        shell: bash

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@417ae3ccd767c252f5661f1ace9f835f9654f2b5

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle Wrapper
        run: ./gradlew build

      - name: Build and Deploy
        if: success()
        run: |
          sudo docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          
          cd ./techdom-collector
          sudo docker build -t techdom-collector .
          IMAGE_TAG=suxxxxhyun/techdom-collector:latest
          echo "Image Tag: $IMAGE_TAG"
          sudo docker tag techdom-collector $IMAGE_TAG
          sudo docker push $IMAGE_TAG

          cd ../techdom-emulator
          sudo docker build -t techdom-emulator .
          IMAGE_TAG=suxxxxhyun/techdom-emulator:latest
          echo "Image Tag: $IMAGE_TAG"
          sudo docker tag techdom-emulator $IMAGE_TAG
          sudo docker push $IMAGE_TAG

      - name: Connect to WAS & Execute Application (techdom-collector)
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.EC2_COLLECTOR_HOST }}
          username: ${{ secrets.EC2_COLLECTOR_USER }}
          key: ${{ secrets.EC2_COLLECTOR_PRIVATE_KEY }}
          script: |
            echo "Pulling and running techdom-collector image on collector EC2..."
            sudo docker pull suxxxxhyun/techdom-collector:latest
            sudo docker stop techdom-collector || true
            sudo docker rm techdom-collector || true
            sudo docker run -d --name techdom-collector -p 8080:8080 suxxxxhyun/techdom-collector:latest

      - name: Connect to WAS & Execute Application (techdom-emulator)
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.EMULATOR_EC2_HOST }}
          username: ${{ secrets.EMULATOR_EC2_USER }}
          key: ${{ secrets.EMULATOR_EC2_PRIVATE_KEY }}
          script: |
            echo "Pulling and running techdom-emulator image on emulator EC2..."
            sudo docker pull suxxxxhyun/techdom-emulator:latest
            sudo docker stop techdom-emulator || true
            sudo docker rm techdom-emulator || true
            sudo docker run -d --name techdom-emulator -p 8081:8080 suxxxxhyun/techdom-emulator:latest


